# Usa imagem oficial do Node 22
FROM node:24

# Entra de trabalho
WORKDIR /app

# Copia arquivos necessários para instalar as dependencia node_modules EM TEMPO DE BUILD
COPY package*.json ./
COPY _mcp.js ./

# Instala dependências + nodemon para "ouvir" as mudanças
RUN npm install -g nodemon && npm install

# Comando padrão ao iniciar o container
ENTRYPOINT ["nodemon", "_mcp.js"]